config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :players

  resources :leagues do
    resources :teams
    resources :league_tournaments, path: "tournaments", as: "tournaments" do
      resources :leaderboards, path: "leaderboard"
    end
  end

  namespace :api do
    namespace :v1 do
      resources :rosters, only: :index
      resources :roster_players, only: :index
    end
  end

  devise_for :users

  get 'welcome/index'

  root to: "leagues#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord

  has_paper_trail

  belongs_to :league_tournament
  has_many :draft_slots

  delegate :league, to: :league_tournament

  def open?
    Time.current >= starts_at && completed_at.blank?
  end

end

app/models/draft_pick.rb
class DraftPick < ApplicationRecord
  belongs_to :draft_slot
  belongs_to :player
end

app/models/draft_slot.rb
class DraftSlot < ApplicationRecord
  belongs_to :draft
  belongs_to :team
  has_one :draft_pick
end

app/models/league.rb
class League < ApplicationRecord

  has_paper_trail

  has_many :league_tournaments
  has_many :tournaments, through: :league_tournaments
  has_many :teams, inverse_of: :league

  def active_league_tournament
    league_tournaments.active.first
  end
end

app/models/league_tournament.rb
class LeagueTournament < ApplicationRecord

  has_paper_trail

  belongs_to :league
  belongs_to :tournament
  has_many :rosters
  has_many :roster_players, through: :rosters
  has_one :draft

  delegate :external_id, to: :tournament
  delegate :start_date, to: :tournament
  delegate :completed, to: :tournament
  delegate :name, to: :tournament

  scope :active, -> { joins(:tournament).merge(Tournament.active) }

end

app/models/player.rb
class Player < ApplicationRecord

  has_paper_trail

  belongs_to :team, inverse_of: :players

  validates :external_id, uniqueness: true

  def name
    "#{first_name} #{last_name}"
  end

end

app/models/roster.rb
class Roster < ActiveRecord::Base

  has_paper_trail

  has_many :roster_players
  has_many :players, through: :roster_players
  belongs_to :team
  belongs_to :league_tournament

  delegate :user, to: :team
  delegate :name, to: :user, prefix: true

  scope :winner, -> { where winner: true }

  accepts_nested_attributes_for :roster_players

  def score
    roster_players.map{|p| p.score}.reduce(:+)
  end

  def final_score
    roster_players.sum(:final_score)
  end
end

app/models/roster_player.rb
class RosterPlayer < ApplicationRecord

  has_paper_trail

  belongs_to :roster
  belongs_to :player

  delegate :external_id, to: :player
  delegate :name, to: :player
  delegate :league_tournament, to: :roster
  delegate :team, to: :roster
  delegate :user, to: :team
  delegate :name, to: :user, prefix: true

  scope :winner, -> { where winner: true }

  def score
    tournament_athlete_score || 0
  end

  def status
    thru || tee_time || "cut"
  end

  private

  def tournament_athlete_score
    @tournament_athlete_score ||= RosterPlayerScoreParser.new(league_tournament.external_id, external_id, league_tournament.completed).score
  end

  def thru
    @thru ||= roster_player_parser.thru
  end

  def tee_time
    @tee_time ||= roster_player_parser.tee_time
  end

  def roster_player_parser
    @roster_player_parser ||= RosterPlayerParser.new(league_tournament.external_id, external_id, league_tournament.completed)
  end
end

app/models/team.rb
class Team < ApplicationRecord

  has_paper_trail

  belongs_to :user, inverse_of: :team
  belongs_to :league, inverse_of: :teams
  has_many :rosters, inverse_of: :team
  delegate :name, to: :user

  def team_wins
    rosters.where(winner: true).count
  end

  def individual_wins
    rosters.collect(&:roster_players).flatten.select(&:winner).count
  end

end

app/models/tournament.rb
class Tournament < ApplicationRecord

  has_paper_trail

  has_many :league_tournaments

  scope :completed, -> { where completed: true }
  scope :incomplete, -> { !completed }
  scope :active, -> { where(completed: false).where('start_date <= ?', Date.current) }

  def status
    @status ||= TournamentDataFetcher.new(external_id, completed).status
  end
end

app/models/tournament_data_fetcher.rb
class TournamentDataFetcher

  def initialize id, completed
    @host = 'http://api.espn.com/'
    @version = 'v1/'
    @tournament_path = 'sports/golf/pga/events/'
    @id = id
    @apiKey = 'dv58z289n3pf5yw4gxrpzrwq'
    @completed = completed
  end

  def athletes
    event["competitors"]
  end

  def round
    event["period"]
  end

  def status
    event["status"]["detail"]
  end

  private

  def response
    Rails.cache.fetch("tournament/#{@id}", expires_in: expiration_time) do
      Hash[HTTParty.get(url)]
    end
  end

  def event
    response["sports"].first["leagues"].first["events"].first["competitions"].first
  end

  def url
    @url ||= [@host, @version, @tournament_path, @id, '?apikey=', @apiKey].join
  end

  def expiration_time
    if @completed
      7.days
    else
      1.minute
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :team, inverse_of: :user

  def name
    [first_name, last_name].join(" ")
  end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def show
    @draft = Draft.includes(draft_slots: :draft_pick).find(params[:id])
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController

  def index
    @league_tournament = LeagueTournament.includes(:league, :tournament).find(params[:tournament_id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @league = League.includes(league_tournaments: :tournament, teams: :user).find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.order(:last_name).all
    render json: @players
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/leaderboards/index.html.erb
<div class="breadcrumb">
  <%= link_to @league_tournament.league.name, league_path(@league_tournament.league), class: "text-blue-600" %>
  <%= link_to @league_tournament.name, league_tournament_path(@league_tournament.league, @league_tournament.tournament), class: "text-blue-600" %>
</div>
<div class="inner-container">
  <h2 class="text-3xl font-bold">Leaderboard</h2>
  <% if !@league_tournament.tournament.completed? %>
    <section class="notice p-2 bg-yellow-100 border-yellow-400 border mt-4">
      <span class="notice-description mr-1"><%= @league_tournament.tournament.status %>
      </span>
    </section>
  <% end %>
  <section class="mt-4">
    <h3 class="text-xl border-b-2">Tournament Leaders</h3>
    <div id="team-leaders" data-league-tournament-id=<%= @league_tournament.id %> />
  </section>
  <section class="mt-6">
    <h3 class="text-xl border-b-2">Player Leaders</h3>
    <div id="player-leaders" data-league-tournament-id=<%= @league_tournament.id %> />
  </section>
</div>

app/views/leaderboards/show.html.erb
<h2 class="text-3xl font-bold"><%= ::Temple::Utils.escape_html((@league.name)) %>
</h2><% if @league.active_league_tournament
 %><section class="notice p-2 bg-yellow-100 border-yellow-400 border mt-4">
<span class="notice-description mr-1">Live!</span>
<%= ::Temple::Utils.escape_html((link_to @league.active_league_tournament.name, league_tournament_leaderboards_path(@league, @league.active_league_tournament), class: "text-blue-600")) %>
</section><% end %><section class="mt-4">
<h3 class="text-xl border-b-2">Teams</h3>
<table class="table-minimal w-full">
<% @league.teams.each do |t|
 %><tr>
<td class="p-2 border-b border-gray-300"><%= ::Temple::Utils.escape_html((link_to t.user.name, league_team_path(@league, t), class: "text-blue-600")) %>
</td></tr><% end %></table></section><section class="mt-6">
<h3 class="text-xl border-b-2">Tournaments</h3>
<table class="table-minimal table-fixed w-full border-gray-300">
<% @league.league_tournaments.sort_by{|t| !t.start_date}.each do |lt|
 %><tr>
<td class="p-2 border-b border-gray-300"><%= ::Temple::Utils.escape_html((link_to lt.name, league_tournament_path(@league, lt), class: "text-blue-600")) %>
</td><td class="p-2 border-b border-gray-300"><%= ::Temple::Utils.escape_html((lt.start_date)) %>
</td><td class="p-2 border-b border-gray-300"><%= ::Temple::Utils.escape_html((link_to "Leaderboard", league_tournament_leaderboards_path(@league, lt), class: "text-blue-600")) %>
</td></tr><% end %></table></section>