config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :players

  resources :leagues do
    resources :teams
    resources :league_tournaments, path: "tournaments", as: "tournaments" do
      resources :leaderboards, path: "leaderboard"
    end
  end

  namespace :api do
    namespace :v1 do
      resources :rosters, only: :index
      resources :roster_players, only: :index
    end
  end

  devise_for :users

  get 'welcome/index'

  root to: "leagues#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord

  has_paper_trail

  belongs_to :league_tournament
  has_many :draft_slots

  delegate :league, to: :league_tournament

  def open?
    Time.current >= starts_at && completed_at.blank?
  end

end

app/models/draft_pick.rb
class DraftPick < ApplicationRecord
  belongs_to :draft_slot
  belongs_to :player
end

app/models/draft_slot.rb
class DraftSlot < ApplicationRecord
  belongs_to :draft
  belongs_to :team
  has_one :draft_pick
end

app/models/league.rb
class League < ApplicationRecord

  has_paper_trail

  has_many :league_tournaments
  has_many :tournaments, through: :league_tournaments
  has_many :teams, inverse_of: :league

  def active_league_tournament
    league_tournaments.active.first
  end
end

app/models/league_tournament.rb
class LeagueTournament < ApplicationRecord

  has_paper_trail

  belongs_to :league
  belongs_to :tournament
  has_many :rosters
  has_many :roster_players, through: :rosters
  has_one :draft

  delegate :external_id, to: :tournament
  delegate :start_date, to: :tournament
  delegate :completed, to: :tournament
  delegate :name, to: :tournament

  scope :active, -> { joins(:tournament).merge(Tournament.active) }

end

app/models/player.rb
class Player < ApplicationRecord

  has_paper_trail

  belongs_to :team, inverse_of: :players

  validates :external_id, uniqueness: true

  def name
    "#{first_name} #{last_name}"
  end

end

app/models/roster.rb
class Roster < ActiveRecord::Base

  has_paper_trail

  has_many :roster_players
  has_many :players, through: :roster_players
  belongs_to :team
  belongs_to :league_tournament

  delegate :user, to: :team
  delegate :name, to: :user, prefix: true

  scope :winner, -> { where winner: true }

  accepts_nested_attributes_for :roster_players

  def score
    roster_players.map{|p| p.score}.reduce(:+)
  end

  def final_score
    roster_players.sum(:final_score)
  end
end

app/models/roster_player.rb
class RosterPlayer < ApplicationRecord

  has_paper_trail

  belongs_to :roster
  belongs_to :player

  delegate :external_id, to: :player
  delegate :name, to: :player
  delegate :league_tournament, to: :roster
  delegate :team, to: :roster
  delegate :user, to: :team
  delegate :name, to: :user, prefix: true

  scope :winner, -> { where winner: true }

  def score
    tournament_athlete_score || 0
  end

  def status
    thru || tee_time || "cut"
  end

  private

  def tournament_athlete_score
    @tournament_athlete_score ||= RosterPlayerScoreParser.new(league_tournament.external_id, external_id, league_tournament.completed).score
  end

  def thru
    @thru ||= roster_player_parser.thru
  end

  def tee_time
    @tee_time ||= roster_player_parser.tee_time
  end

  def roster_player_parser
    @roster_player_parser ||= RosterPlayerParser.new(league_tournament.external_id, external_id, league_tournament.completed)
  end
end

app/models/team.rb
class Team < ApplicationRecord

  has_paper_trail

  belongs_to :user, inverse_of: :team
  belongs_to :league, inverse_of: :teams
  has_many :rosters, inverse_of: :team
  delegate :name, to: :user

  def team_wins
    rosters.where(winner: true).count
  end

  def individual_wins
    rosters.collect(&:roster_players).flatten.select(&:winner).count
  end

end

app/models/tournament.rb
class Tournament < ApplicationRecord

  has_paper_trail

  has_many :league_tournaments

  scope :completed, -> { where completed: true }
  scope :incomplete, -> { !completed }
  scope :active, -> { where(completed: false).where('start_date <= ?', Date.current) }

  def status
    @status ||= TournamentDataFetcher.new(external_id, completed).status
  end
end

app/models/tournament_data_fetcher.rb
class TournamentDataFetcher

  def initialize id, completed
    @host = 'http://api.espn.com/'
    @version = 'v1/'
    @tournament_path = 'sports/golf/pga/events/'
    @id = id
    @apiKey = 'dv58z289n3pf5yw4gxrpzrwq'
    @completed = completed
  end

  def athletes
    event["competitors"]
  end

  def round
    event["period"]
  end

  def status
    event["status"]["detail"]
  end

  private

  def response
    Rails.cache.fetch("tournament/#{@id}", expires_in: expiration_time) do
      Hash[HTTParty.get(url)]
    end
  end

  def event
    response["sports"].first["leagues"].first["events"].first["competitions"].first
  end

  def url
    @url ||= [@host, @version, @tournament_path, @id, '?apikey=', @apiKey].join
  end

  def expiration_time
    if @completed
      7.days
    else
      1.minute
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :team, inverse_of: :user

  def name
    [first_name, last_name].join(" ")
  end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def show
    @draft = Draft.includes(draft_slots: :draft_pick).find(params[:id])
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @league = League.includes(league_tournaments: :tournament, teams: :user).find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.order(:last_name).all
    render json: @players
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-green-300">
  <div class="footer-logo text-center mb-4">
    <img class="h-12 mx-auto" src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/EmeraldLake.jpg" />
  </div>
  <div class="footer-links text-center overflow-hidden flex justify-center px-4 text-white">
    <ul class="mx-16">
      <li>
        <h3 class="font-bold">Content</h3>
      </li>
      <li>
        <%= link_to "Home", root_path, class: "text-gray-300" %>
      </li>
      <li>
        <%= link_to "Leagues", leagues_path, class: "text-gray-300" %>
      </li>
    </ul>
    <ul class="mx-16">
      <li>
        <h3 class="font-bold">Follow Us</h3>
      </li>
      <li>
        <a class="text-gray-300" href="http://twitter.com/dubilla" target="_blank">Twitter</a>
      </li>
      <li>
        <a class="text-gray-300" href="http://github.com/dubilla/Augusta" target="_blank">GitHub</a>
      </li>
    </ul>
    <ul class="mx-16">
      <li>
        <h3 class="font-bold">Contact</h3>
      </li>
      <li>
        <a class="text-gray-300" href="mailto:dan.ubilla+augusta@gmail.com">Email</a>
      </li>
    </ul>
  </div>
  <p class="text-center text-gray-300 text-xs">Made in New York, 2014</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navigation bg-green-300 flow-root">
  <div class="menu-wrapper mx-auto max-w-7xl">
    <a class="logo float-left pl-4 pr-8 logo" href="javascript:void(0)">
      <img class="max-h-16 py-3" src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" />
    </a>
    <div class="nav float-left mt-3">
      <ul id="navigation-menu">
        <li class="nav-link text-gray-200 leading-10">
          <%= link_to "Leagues", leagues_path %>
        </li>
      </ul>
    </div>
    <div class="navigation-tools float-right pr-4 mt-3">
      <% if user_signed_in? %>
        <div class="signed-in-wrapper">
          <span class="text">
            Hi, <%= current_user.first_name %>
          </span>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out" %>
        </div>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "sign-up block p-1 bg-green-200 float-left text-white" %>
      <div class="sign-in-wrapper float-right mt-1">
        <span class="text text-white mx-2">or</span>
        <%= link_to "Sign In", new_user_session_path, class: "sign-in text-white"  %>
      </div>
    <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Augusta</title>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application" %>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="outer-container max-w-7xl mx-auto p-8">
      <div class="container">
        <div id="notice">
          <%= notice %>
        </div>

        <%= yield %>

      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>